# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subs', '0002_remove_subscription_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriptions_added', models.ManyToManyField(related_name='_subscriptionlog_subscriptions_added_+', to='subs.Subscription')),
                ('subscriptions_removed', models.ManyToManyField(related_name='_subscriptionlog_subscriptions_removed_+', to='subs.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
